jobs:
  - name: image-manifest
    type: manifest
    steps:
      - IN: box-opts
      - IN: deploy-image
        pull: false
        versionName: latest
      - IN: image-params
        applyTo:
          - deploy-image
      - TASK: managed

  - name: build-image
    type: runSh
    steps:
      - IN: image-manifest
      - IN: infra-repo
      - IN: image-params
      - TASK:
        - script: "echo 'executing custom task'"
        - script: ./IN/infra-repo/gitRepo/provision.sh
        - script: echo $SSH_AUTH_SOCK && echo $SSH_AGENT_PID
    on_success:
      - script: echo 'This block executes after TASK section executes successfully'
